title: Python Financial Tookit - pftk
email: charlesg@unixrealm.com
description: >- # this means to ignore newlines until "baseurl:"
  The Pyhon Financial Toolkit (pftk) is a Python-based open source software framework designed to support portfolio construction and management.
twitter_username: unixrealm
github_username:  charlesg
repository: charlesg/pftk


# Build settings
theme: jekyll-theme-architect
